Add user guide chapter 2 to tutorials
ASUS-AICS/LibMultiLabel pull request #290
Opened 2023-04-11 10:00 UTC by Tonmoregulus

## What does this PR do?

- Add user guide chapter 2 : Parameter Selection for Neural Networks to tutorials
- Add a link to the new tutorials part : Parameter Selection for Neural Networks to tutorials at Command Line Interface/QuickStart/Training, Prediction, and Hyper-parameter Search for Neural Networks/Hyper-parameter Search so that users could find more information about grid search for parameters in neural networks

## Test CLI & API (`bash tests/autotest.sh`)
Test APIs used by main.py.
- [ ] Test Pass
  - (Copy and paste the last outputted line here.)
- [ ] Not Applicable (i.e., the PR does not include API changes.)

## Check API Document
If any new APIs are added, please check if the description of the APIs is added to API document. 
- [ ] API document is updated ([linear](https://www.csie.ntu.edu.tw/~cjlin/libmultilabel/api/linear.html), [nn](https://www.csie.ntu.edu.tw/~cjlin/libmultilabel/api/nn.html))
- [ ] Not Applicable (i.e., the PR does not include API changes.)

## Test quickstart & API (`bash tests/docs/test_changed_document.sh`)
If any APIs in quickstarts or tutorials are modified, please run this test to check if the current examples can run correctly after the modified APIs are released.

2023-04-19 13:21 UTC, cjlin1 commented on docs/tutorial.rst
> +* `Parameter Selection for Neural Networks <tutorials/Parameter_Selection_for_Neural_Networks.html>`_
why tutorials vs ./auto_examples ?

2023-04-19 13:22 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +The following example demonstrates how the BiGRU model performs differently on the EUR-Lex data set with two parameter sets.
need to say where data is

2023-04-19 13:22 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +grid search for parameters
```suggestion
Grid Search over Parameters

```

2023-04-19 13:23 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +`default configuration file <https://github.com/ASUS-AICS/LibMultiLabel/blob/master/example_config/EUR-Lex/bigru_lwan.yml>`_
can we do relative path here

2023-04-19 13:25 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +4% lower than the first one.This demonstrates the importance of parameter selection.
```suggestion
4% lower than the first one. This demonstrates the importance of parameter selection.

```

2023-04-19 13:25 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +First in the configuration file, we specify a grid search on the following parameters to get the best BiGRU model
```suggestion
In the configuration file, we specify a grid search on the following parameters to get the best BiGRU model

```

2023-04-19 13:26 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +on the EUR-Lex data set.
```suggestion

```

2023-04-19 13:27 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +Here We set the embed cache dir to .vector cache to avoid downloading pre-trained embeddings repeatedly for each configuration.
```suggestion
We set the embed cache dir to .vector cache to avoid downloading pre-trained embeddings repeatedly for each configuration.

```

2023-04-19 13:28 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +Here We set the embed cache dir to .vector cache to avoid downloading pre-trained embeddings repeatedly for each configuration.
embed cache dir   is wrong.. Need to represent it as a parameter

2023-04-19 13:28 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +The process find the best parameter set of ``learning_rate=0.0003``, ``embed_dropout=0.4``, ``encoder_dropout=0.4``, and ``rnn_dim=512``.
```suggestion
The process finds the best parameter set of ``learning_rate=0.0003``, ``embed_dropout=0.4``, ``encoder_dropout=0.4``, and ``rnn_dim=512``. 

```

2023-04-19 13:29 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +. Additionally, after the search process, the program applies the best parameters to obtain the final model by adding
```suggestion
After the search process, the program applies the best parameters to obtain the final model by adding 

```

2023-04-19 13:30 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +`bigru_lwan configuration file <https://github.com/ASUS-AICS/LibMultiLabel/blob/master/example_config/EUR-Lex/bigru_lwan.yml>`_
```suggestion
`bigru_lwan configuration file <https://github.com/ASUS-AICS/LibMultiLabel/blob/master/example_config/EUR-Lex/bigru_lwan.yml>`.

```

is this the way to have . in the end?

2023-04-19 13:30 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +Direct selected parameter
```suggestion
Direct Trying Some Parameters

```

2023-04-19 13:31 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +early stopping techniques
```suggestion
Early Stopping of the Parameter Search 

```

2023-04-19 13:31 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +early stopping techniques
why ref was removed?

2023-04-19 13:32 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +Here we demonstrate an example of applying an ASHA (Asynchronous Successive Halving Algorithm) Scheduler .
ref?

2023-04-19 13:32 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +.. list-table:: Neural networks (BiGRU) Experiments on the EUR-Lex data set
table caption not needed

2023-04-19 13:32 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +     - Training Time(GPU)
```suggestion
     - Training Time (GPU)

```

2023-04-19 13:33 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +
before the table should give the GPU configuration used.

2023-04-20 23:16 UTC, Eleven1Liu requested changes

2023-04-20 23:16 UTC, Eleven1Liu commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +
Remove line breaks.

```suggestion
```

2023-04-30 05:50 UTC, cjlin1 commented on docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
> +A summary of results is in the following table.Four Nvidia Tesla V100 GPUs are used in this experiment.
```suggestion
A summary of results is in the following table. Four Nvidia Tesla V100 GPUs were used in this experiment.

```

2023-05-01 11:59 UTC, merged