Modify no_merge_train_val to retrain.
ASUS-AICS/LibMultiLabel pull request #332
Opened 2023-09-09 10:30 UTC by Gordon119

## What does this PR do?

As title, the `no_merge_train_val` in `search_params.py` can be confused with the `merge_train_val` in `torch_trainer.py`. Although they both indicate merging training and validation set, the former one is used for retraining. This PR modify the name of it.

## Test CLI & API (`bash tests/autotest.sh`)
Test APIs used by main.py.
- [ ] Test Pass
  - (Copy and paste the last outputted line here.)
- [x] Not Applicable (i.e., the PR does not include API changes.)

## Check API Document
If any new APIs are added, please check if the description of the APIs is added to API document. 
- [ ] API document is updated ([linear](https://www.csie.ntu.edu.tw/~cjlin/libmultilabel/api/linear.html), [nn](https://www.csie.ntu.edu.tw/~cjlin/libmultilabel/api/nn.html))
- [x] Not Applicable (i.e., the PR does not include API changes.)

## Test quickstart & API (`bash tests/docs/test_changed_document.sh`)
If any APIs in quickstarts or tutorials are modified, please run this test to check if the current examples can run correctly after the modified APIs are released.

2023-09-10 22:05 UTC, cjlin1 approved these changes

2023-09-11 11:44 UTC, Eleven1Liu commented on search_params.py
> +        best_config.retrain = False
Is `best_config.merge_train_val` used in main.py? ([link](https://github.com/ASUS-AICS/LibMultiLabel/blob/f325f4877c91751c2075307eb2b7bc486892e5e2/main.py#L48))

2023-09-11 11:47 UTC, Eleven1Liu requested changes
Please check when to use `config.merge_train_val` and when to use `args.retrain`.

2023-09-14 12:46 UTC, Eleven1Liu approved these changes

2023-09-15 04:31 UTC, merged