A Lighter Timer
ASUS-AICS/LibMultiLabel pull request #350
Opened 2024-01-17 11:54 UTC by donglihe-hub

## What does this PR do?

In many cases, developers may want to measure the running time of functions. The original Timer in LibMultiLabel is not more convenient than using the time package directly. The new lightweight timer is a decorator and is more handy.

usage 1:
```python
import time
from libmultilabel.common_utils import timer

@timer
def a ():
    time.sleep(10)

a()
```
```
INFO:lightning.pytorch.utilities.rank_zero:Finished 'a' in 3.00 seconds
```
usage 2:
```python
def a ():
    time.sleep(3)

timer(a)()
```
```
INFO:lightning.pytorch.utilities.rank_zero:Finished 'a' in 3.00 seconds
```

## Test CLI & API (`bash tests/autotest.sh`)
Test APIs used by main.py.
- [ ] Test Pass
  - (Copy and paste the last outputted line here.)
- [ ] Not Applicable (i.e., the PR does not include API changes.)

## Check API Document
If any new APIs are added, please check if the description of the APIs is added to API document. 
- [ ] API document is updated ([linear](https://www.csie.ntu.edu.tw/~cjlin/libmultilabel/api/linear.html), [nn](https://www.csie.ntu.edu.tw/~cjlin/libmultilabel/api/nn.html))
- [ ] Not Applicable (i.e., the PR does not include API changes.)

## Test quickstart & API (`bash tests/docs/test_changed_document.sh`)
If any APIs in quickstarts or tutorials are modified, please run this test to check if the current examples can run correctly after the modified APIs are released.

2024-01-19 07:48 UTC, Eleven1Liu commented
@Sinacam Review

2024-01-21 23:57 UTC, Eleven1Liu commented on libmultilabel/common_utils.py
> +    """Emit info-level wall time only on global rank 0."""
Why global rank 0 here?

2024-01-22 00:19 UTC, Eleven1Liu requested changes
Please update the comment.

2024-01-22 06:14 UTC, donglihe-hub commented on libmultilabel/common_utils.py
> +    """Emit info-level wall time only on global rank 0."""
Removed

2024-01-22 06:41 UTC, Eleven1Liu approved these changes

2024-01-22 06:41 UTC, merged