Add normalize as an argument
ASUS-AICS/LibMultiLabel pull request #66
Opened 2021-07-26 04:38 UTC by Eleven1Liu

**Description**  Add `--normalize` to config to decide if we should normalize the word embeddings by:
```
vector = vector  / float(np.linalg.norm(vector) + 1e-6)
```

2021-07-26 05:56 UTC, Eleven1Liu commented on libmultilabel/data_utils.py
> +    normalize=True
set `False`

2021-07-26 07:31 UTC, sian-chen requested changes

2021-07-26 07:31 UTC, sian-chen commented on main.py
> +    parser.add_argument('--normalize', type=bool, default=False,
Use `action='store_true'` for flags.
https://docs.python.org/3/library/argparse.html#action

```suggestion
    parser.add_argument('--normalize', action='store_true',
```

2021-07-26 08:39 UTC, sian-chen approved these changes

2021-07-26 10:16 UTC, merged

2021-07-28 08:53 UTC, cjlin1 commented on main.py
> +                        help='Whether the word embeddings divide by `float(np.linalg.norm(vector) + 1e-6)` (default: %(default)s)')
this description isn't good. "vector" is unclear here and it's not good to have the code np.xxx in the help.
I think we should just say
Whether the embeddings of each word is normalized to a unit vector

2021-07-28 09:04 UTC, cjlin1 commented on libmultilabel/data_utils.py
> +        embedding_weights = get_embedding_weights_from_file(vocabs, embed_file, silent, normalize)
so the "normalize" option is only for user-specified embeddings?  If I am a user I would think that this is applied to all situations. Need some discussion tomorrow